version: '3.7'
volumes:
  data:

services:
  mysql-db:
    build: .
    ports:
     - 3306:3306
    env:
      - MYSQL_ROOT_PASSWORD: 'mysqlpassword'
      - MYSQL_DATABASE: 'futebol'
    volumes:
    - data:/var/lib/mysql