version: '3.9'
services:
  database:
    build: ./database
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=bandtec
      - MYSQL_DATABASE=projeto_pi
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
